/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AfpRouteImport } from './routes/afp'
import { Route as IndexRouteImport } from './routes/index'

const AfpRoute = AfpRouteImport.update({
  id: '/afp',
  path: '/afp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afp': typeof AfpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afp': typeof AfpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afp': typeof AfpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/afp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/afp'
  id: '__root__' | '/' | '/afp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfpRoute: typeof AfpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/afp': {
      id: '/afp'
      path: '/afp'
      fullPath: '/afp'
      preLoaderRoute: typeof AfpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfpRoute: AfpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
